/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RegisterEmailRouteImport } from './routes/register-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HeaderLayoutRouteImport } from './routes/_header-layout'
import { Route as HeaderLayoutIndexRouteImport } from './routes/_header-layout/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as LinkAccountEmailRouteImport } from './routes/link-account.$email'
import { Route as ConfirmLinkingEmailRouteImport } from './routes/confirm-linking.$email'
import { Route as HeaderLayoutTagsRouteImport } from './routes/_header-layout/tags'
import { Route as HeaderLayoutSavesRouteImport } from './routes/_header-layout/saves'
import { Route as HeaderLayoutHomeRouteImport } from './routes/_header-layout/home'
import { Route as HeaderLayoutHighlightsRouteImport } from './routes/_header-layout/highlights'
import { Route as HeaderLayoutFeedsRouteImport } from './routes/_header-layout/feeds'
import { Route as HeaderLayoutExportRouteImport } from './routes/_header-layout/export'
import { Route as HeaderLayoutCollectionsRouteImport } from './routes/_header-layout/collections'
import { Route as HeaderLayoutSavesIndexRouteImport } from './routes/_header-layout/saves/index'
import { Route as SignUpEmailTokenRouteImport } from './routes/sign-up.$email.$token'
import { Route as HeaderLayoutSavesFavouritesRouteImport } from './routes/_header-layout/saves/favourites'
import { Route as HeaderLayoutSavesArchiveRouteImport } from './routes/_header-layout/saves/archive'
import { Route as HeaderLayoutFeedsCategoryRouteImport } from './routes/_header-layout/feeds/$category'
import { Route as HeaderLayoutFeedsCategoryFeedRouteImport } from './routes/_header-layout/feeds/$category/$feed'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEmailRoute = RegisterEmailRouteImport.update({
  id: '/register-email',
  path: '/register-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRoute = HeaderLayoutRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutIndexRoute = HeaderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkAccountEmailRoute = LinkAccountEmailRouteImport.update({
  id: '/link-account/$email',
  path: '/link-account/$email',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmLinkingEmailRoute = ConfirmLinkingEmailRouteImport.update({
  id: '/confirm-linking/$email',
  path: '/confirm-linking/$email',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutTagsRoute = HeaderLayoutTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutSavesRoute = HeaderLayoutSavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutHomeRoute = HeaderLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutHighlightsRoute = HeaderLayoutHighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutFeedsRoute = HeaderLayoutFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutExportRoute = HeaderLayoutExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutCollectionsRoute = HeaderLayoutCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutSavesIndexRoute = HeaderLayoutSavesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutSavesRoute,
} as any)
const SignUpEmailTokenRoute = SignUpEmailTokenRouteImport.update({
  id: '/sign-up/$email/$token',
  path: '/sign-up/$email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutSavesFavouritesRoute =
  HeaderLayoutSavesFavouritesRouteImport.update({
    id: '/favourites',
    path: '/favourites',
    getParentRoute: () => HeaderLayoutSavesRoute,
  } as any)
const HeaderLayoutSavesArchiveRoute =
  HeaderLayoutSavesArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => HeaderLayoutSavesRoute,
  } as any)
const HeaderLayoutFeedsCategoryRoute =
  HeaderLayoutFeedsCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => HeaderLayoutFeedsRoute,
  } as any)
const HeaderLayoutFeedsCategoryFeedRoute =
  HeaderLayoutFeedsCategoryFeedRouteImport.update({
    id: '/$feed',
    path: '/$feed',
    getParentRoute: () => HeaderLayoutFeedsCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/register-email': typeof RegisterEmailRoute
  '/sign-in': typeof SignInRoute
  '/collections': typeof HeaderLayoutCollectionsRoute
  '/export': typeof HeaderLayoutExportRoute
  '/feeds': typeof HeaderLayoutFeedsRouteWithChildren
  '/highlights': typeof HeaderLayoutHighlightsRoute
  '/home': typeof HeaderLayoutHomeRoute
  '/saves': typeof HeaderLayoutSavesRouteWithChildren
  '/tags': typeof HeaderLayoutTagsRoute
  '/confirm-linking/$email': typeof ConfirmLinkingEmailRoute
  '/link-account/$email': typeof LinkAccountEmailRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/': typeof HeaderLayoutIndexRoute
  '/feeds/$category': typeof HeaderLayoutFeedsCategoryRouteWithChildren
  '/saves/archive': typeof HeaderLayoutSavesArchiveRoute
  '/saves/favourites': typeof HeaderLayoutSavesFavouritesRoute
  '/sign-up/$email/$token': typeof SignUpEmailTokenRoute
  '/saves/': typeof HeaderLayoutSavesIndexRoute
  '/feeds/$category/$feed': typeof HeaderLayoutFeedsCategoryFeedRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/register-email': typeof RegisterEmailRoute
  '/sign-in': typeof SignInRoute
  '/collections': typeof HeaderLayoutCollectionsRoute
  '/export': typeof HeaderLayoutExportRoute
  '/feeds': typeof HeaderLayoutFeedsRouteWithChildren
  '/highlights': typeof HeaderLayoutHighlightsRoute
  '/home': typeof HeaderLayoutHomeRoute
  '/tags': typeof HeaderLayoutTagsRoute
  '/confirm-linking/$email': typeof ConfirmLinkingEmailRoute
  '/link-account/$email': typeof LinkAccountEmailRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/': typeof HeaderLayoutIndexRoute
  '/feeds/$category': typeof HeaderLayoutFeedsCategoryRouteWithChildren
  '/saves/archive': typeof HeaderLayoutSavesArchiveRoute
  '/saves/favourites': typeof HeaderLayoutSavesFavouritesRoute
  '/sign-up/$email/$token': typeof SignUpEmailTokenRoute
  '/saves': typeof HeaderLayoutSavesIndexRoute
  '/feeds/$category/$feed': typeof HeaderLayoutFeedsCategoryFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_header-layout': typeof HeaderLayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register-email': typeof RegisterEmailRoute
  '/sign-in': typeof SignInRoute
  '/_header-layout/collections': typeof HeaderLayoutCollectionsRoute
  '/_header-layout/export': typeof HeaderLayoutExportRoute
  '/_header-layout/feeds': typeof HeaderLayoutFeedsRouteWithChildren
  '/_header-layout/highlights': typeof HeaderLayoutHighlightsRoute
  '/_header-layout/home': typeof HeaderLayoutHomeRoute
  '/_header-layout/saves': typeof HeaderLayoutSavesRouteWithChildren
  '/_header-layout/tags': typeof HeaderLayoutTagsRoute
  '/confirm-linking/$email': typeof ConfirmLinkingEmailRoute
  '/link-account/$email': typeof LinkAccountEmailRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_header-layout/': typeof HeaderLayoutIndexRoute
  '/_header-layout/feeds/$category': typeof HeaderLayoutFeedsCategoryRouteWithChildren
  '/_header-layout/saves/archive': typeof HeaderLayoutSavesArchiveRoute
  '/_header-layout/saves/favourites': typeof HeaderLayoutSavesFavouritesRoute
  '/sign-up/$email/$token': typeof SignUpEmailTokenRoute
  '/_header-layout/saves/': typeof HeaderLayoutSavesIndexRoute
  '/_header-layout/feeds/$category/$feed': typeof HeaderLayoutFeedsCategoryFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/register-email'
    | '/sign-in'
    | '/collections'
    | '/export'
    | '/feeds'
    | '/highlights'
    | '/home'
    | '/saves'
    | '/tags'
    | '/confirm-linking/$email'
    | '/link-account/$email'
    | '/reset-password/$token'
    | '/'
    | '/feeds/$category'
    | '/saves/archive'
    | '/saves/favourites'
    | '/sign-up/$email/$token'
    | '/saves/'
    | '/feeds/$category/$feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/register-email'
    | '/sign-in'
    | '/collections'
    | '/export'
    | '/feeds'
    | '/highlights'
    | '/home'
    | '/tags'
    | '/confirm-linking/$email'
    | '/link-account/$email'
    | '/reset-password/$token'
    | '/'
    | '/feeds/$category'
    | '/saves/archive'
    | '/saves/favourites'
    | '/sign-up/$email/$token'
    | '/saves'
    | '/feeds/$category/$feed'
  id:
    | '__root__'
    | '/_header-layout'
    | '/forgot-password'
    | '/register-email'
    | '/sign-in'
    | '/_header-layout/collections'
    | '/_header-layout/export'
    | '/_header-layout/feeds'
    | '/_header-layout/highlights'
    | '/_header-layout/home'
    | '/_header-layout/saves'
    | '/_header-layout/tags'
    | '/confirm-linking/$email'
    | '/link-account/$email'
    | '/reset-password/$token'
    | '/_header-layout/'
    | '/_header-layout/feeds/$category'
    | '/_header-layout/saves/archive'
    | '/_header-layout/saves/favourites'
    | '/sign-up/$email/$token'
    | '/_header-layout/saves/'
    | '/_header-layout/feeds/$category/$feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterEmailRoute: typeof RegisterEmailRoute
  SignInRoute: typeof SignInRoute
  ConfirmLinkingEmailRoute: typeof ConfirmLinkingEmailRoute
  LinkAccountEmailRoute: typeof LinkAccountEmailRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  SignUpEmailTokenRoute: typeof SignUpEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-email': {
      id: '/register-email'
      path: '/register-email'
      fullPath: '/register-email'
      preLoaderRoute: typeof RegisterEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/': {
      id: '/_header-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-account/$email': {
      id: '/link-account/$email'
      path: '/link-account/$email'
      fullPath: '/link-account/$email'
      preLoaderRoute: typeof LinkAccountEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-linking/$email': {
      id: '/confirm-linking/$email'
      path: '/confirm-linking/$email'
      fullPath: '/confirm-linking/$email'
      preLoaderRoute: typeof ConfirmLinkingEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/tags': {
      id: '/_header-layout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof HeaderLayoutTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/saves': {
      id: '/_header-layout/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof HeaderLayoutSavesRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/home': {
      id: '/_header-layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HeaderLayoutHomeRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/highlights': {
      id: '/_header-layout/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HeaderLayoutHighlightsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/feeds': {
      id: '/_header-layout/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof HeaderLayoutFeedsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/export': {
      id: '/_header-layout/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof HeaderLayoutExportRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/collections': {
      id: '/_header-layout/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof HeaderLayoutCollectionsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/saves/': {
      id: '/_header-layout/saves/'
      path: '/'
      fullPath: '/saves/'
      preLoaderRoute: typeof HeaderLayoutSavesIndexRouteImport
      parentRoute: typeof HeaderLayoutSavesRoute
    }
    '/sign-up/$email/$token': {
      id: '/sign-up/$email/$token'
      path: '/sign-up/$email/$token'
      fullPath: '/sign-up/$email/$token'
      preLoaderRoute: typeof SignUpEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/saves/favourites': {
      id: '/_header-layout/saves/favourites'
      path: '/favourites'
      fullPath: '/saves/favourites'
      preLoaderRoute: typeof HeaderLayoutSavesFavouritesRouteImport
      parentRoute: typeof HeaderLayoutSavesRoute
    }
    '/_header-layout/saves/archive': {
      id: '/_header-layout/saves/archive'
      path: '/archive'
      fullPath: '/saves/archive'
      preLoaderRoute: typeof HeaderLayoutSavesArchiveRouteImport
      parentRoute: typeof HeaderLayoutSavesRoute
    }
    '/_header-layout/feeds/$category': {
      id: '/_header-layout/feeds/$category'
      path: '/$category'
      fullPath: '/feeds/$category'
      preLoaderRoute: typeof HeaderLayoutFeedsCategoryRouteImport
      parentRoute: typeof HeaderLayoutFeedsRoute
    }
    '/_header-layout/feeds/$category/$feed': {
      id: '/_header-layout/feeds/$category/$feed'
      path: '/$feed'
      fullPath: '/feeds/$category/$feed'
      preLoaderRoute: typeof HeaderLayoutFeedsCategoryFeedRouteImport
      parentRoute: typeof HeaderLayoutFeedsCategoryRoute
    }
  }
}

interface HeaderLayoutFeedsCategoryRouteChildren {
  HeaderLayoutFeedsCategoryFeedRoute: typeof HeaderLayoutFeedsCategoryFeedRoute
}

const HeaderLayoutFeedsCategoryRouteChildren: HeaderLayoutFeedsCategoryRouteChildren =
  {
    HeaderLayoutFeedsCategoryFeedRoute: HeaderLayoutFeedsCategoryFeedRoute,
  }

const HeaderLayoutFeedsCategoryRouteWithChildren =
  HeaderLayoutFeedsCategoryRoute._addFileChildren(
    HeaderLayoutFeedsCategoryRouteChildren,
  )

interface HeaderLayoutFeedsRouteChildren {
  HeaderLayoutFeedsCategoryRoute: typeof HeaderLayoutFeedsCategoryRouteWithChildren
}

const HeaderLayoutFeedsRouteChildren: HeaderLayoutFeedsRouteChildren = {
  HeaderLayoutFeedsCategoryRoute: HeaderLayoutFeedsCategoryRouteWithChildren,
}

const HeaderLayoutFeedsRouteWithChildren =
  HeaderLayoutFeedsRoute._addFileChildren(HeaderLayoutFeedsRouteChildren)

interface HeaderLayoutSavesRouteChildren {
  HeaderLayoutSavesArchiveRoute: typeof HeaderLayoutSavesArchiveRoute
  HeaderLayoutSavesFavouritesRoute: typeof HeaderLayoutSavesFavouritesRoute
  HeaderLayoutSavesIndexRoute: typeof HeaderLayoutSavesIndexRoute
}

const HeaderLayoutSavesRouteChildren: HeaderLayoutSavesRouteChildren = {
  HeaderLayoutSavesArchiveRoute: HeaderLayoutSavesArchiveRoute,
  HeaderLayoutSavesFavouritesRoute: HeaderLayoutSavesFavouritesRoute,
  HeaderLayoutSavesIndexRoute: HeaderLayoutSavesIndexRoute,
}

const HeaderLayoutSavesRouteWithChildren =
  HeaderLayoutSavesRoute._addFileChildren(HeaderLayoutSavesRouteChildren)

interface HeaderLayoutRouteChildren {
  HeaderLayoutCollectionsRoute: typeof HeaderLayoutCollectionsRoute
  HeaderLayoutExportRoute: typeof HeaderLayoutExportRoute
  HeaderLayoutFeedsRoute: typeof HeaderLayoutFeedsRouteWithChildren
  HeaderLayoutHighlightsRoute: typeof HeaderLayoutHighlightsRoute
  HeaderLayoutHomeRoute: typeof HeaderLayoutHomeRoute
  HeaderLayoutSavesRoute: typeof HeaderLayoutSavesRouteWithChildren
  HeaderLayoutTagsRoute: typeof HeaderLayoutTagsRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutCollectionsRoute: HeaderLayoutCollectionsRoute,
  HeaderLayoutExportRoute: HeaderLayoutExportRoute,
  HeaderLayoutFeedsRoute: HeaderLayoutFeedsRouteWithChildren,
  HeaderLayoutHighlightsRoute: HeaderLayoutHighlightsRoute,
  HeaderLayoutHomeRoute: HeaderLayoutHomeRoute,
  HeaderLayoutSavesRoute: HeaderLayoutSavesRouteWithChildren,
  HeaderLayoutTagsRoute: HeaderLayoutTagsRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterEmailRoute: RegisterEmailRoute,
  SignInRoute: SignInRoute,
  ConfirmLinkingEmailRoute: ConfirmLinkingEmailRoute,
  LinkAccountEmailRoute: LinkAccountEmailRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  SignUpEmailTokenRoute: SignUpEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
